% % This script takes several temperature files generated by SOundTraps,
% % concatenate them into a single file and converts timestamps to a human readable
% % format. Press Run, select the ST files, then wait for the script to run.
% % The output file (concatenated_temperatures_UTC.csv) will be created in the
% % same folder as the ST temp files.
% 
% clear all
% close all
% clc
% 
% [filename, pathname, filterindex] = uigetfile('*.temp.csv','Select SoundTrap temperature files.', 'MultiSelect', 'on');
% 
% %% concatenate files
% Table=[];
% for i = 1: length(filename)
%     Table = [Table ; readtable([pathname, filename{i}])];
% end
% 
% %% Sort by increasing time
% Table = sortrows(Table);
% 
% %% Convert times to human readable format
% Table.unixTime = datestr(Table.unixTime/86400 + datenum(1970,1,1));
% Table.Properties.VariableNames = {'utcTime' 'degreesC'};
% %% Save as csv
% writetable(Table,[pathname,'concatenated_temperatures_UTC.csv']);
% 
% disp('Done.')
% 
% 
